### ISSUE TITLE
Add several papers about Voice Conversion

### ISSUE THREAD

**Issue by Miralan** [wenet-e2e/speech-synthesis-paper#3]
Recommend some papers about Voice Conversion.

Seq2Seq（ASR+TTS）:

1.Transferring Source Style in Non-Parallel Voice Conversion

[link](https://arxiv.org/abs/2005.09178)

Auto-encoder:

2.SPEECHFLOW：Unsupervised speech decomposition via triple information bottleneck

[link](https://arxiv.org/pdf/2004.11284)（2020 ICML）

3.F0-AutoVC：F0-consistent many-to-many non-parallel voice conversion via conditional autoencoder

[link](https://arxiv.org/abs/2004.07370)（2020 ICASSP）

VQ-VAE:

4.Unsupervised speech representation learning using WaveNet autoencoders

[link](https://arxiv.org/abs/1901.08810)（IEEE/ACM Trans)

5.Vector-quantized neural networks for acoustic unit discovery in the ZeroSpeech 2020 challenge

 [link](https://arxiv.org/abs/2005.09409) (2020 Interspeech)

6.One-shot voice conversion by vector quantization 

[link](https://ieeexplore.ieee.org/abstract/document/9053854) (2020 ICASSP)

**Comment by xcmyz** [comment]
> Recommend some papers about Voice Conversion.
> 
> Seq2Seq（ASR+TTS）:
> 
> 1.Transferring Source Style in Non-Parallel Voice Conversion
> 
> [link](https://arxiv.org/abs/2005.09178)
> 
> Auto-encoder:
> 
> 2.SPEECHFLOW：Unsupervised speech decomposition via triple information bottleneck
> 
> [link](https://arxiv.org/pdf/2004.11284)（2020 ICML）
> 
> 3.F0-AutoVC：F0-consistent many-to-many non-parallel voice conversion via conditional autoencoder
> 
> [link](https://arxiv.org/abs/2004.07370)（2020 ICASSP）
> 
> VQ-VAE:
> 
> 4.Unsupervised speech representation learning using WaveNet autoencoders
> 
> [link](https://arxiv.org/abs/1901.08810)（IEEE/ACM Trans)
> 
> 5.Vector-quantized neural networks for acoustic unit discovery in the ZeroSpeech 2020 challenge
> 
> [link](https://arxiv.org/abs/2005.09409) (2020 Interspeech)
> 
> 6.One-shot voice conversion by vector quantization
> 
> [link](https://ieeexplore.ieee.org/abstract/document/9053854) (2020 ICASSP)

Thank you!

**Comment by Miralan** [comment]
A new vocoder : 
DiffWave: A Versatile Diffusion Model for Audio Synthesis
[link](https://arxiv.org/abs/2009.09761)
Very similar to wavegrad~
